# Etapa 1: Construcción (Build)
FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Compila la app para producción. Esto crea la carpeta /dist
RUN npm run build -- --configuration production

# Etapa 2: Servidor Web (Nginx)
FROM nginx:alpine
# Copiamos los archivos compilados de la etapa anterior al servidor Nginx
COPY --from=build /app/dist/cli /usr/share/nginx/html
# Copiamos una configuración básica de Nginx (opcional, pero recomendada para Angular)
COPY nginx-custom.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]